### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Renuka",
  "email": "renuka@gmail.com"
}

###
### Get Users
GET http://localhost:8080/api/users
### Create Internship (POST)
POST http://localhost:8080/api/internships/user/1
Content-Type: application/json

{
  "companyName": "Google",
  "role": "Backend Intern",
  "status": "APPLIED",
  "appliedDate": "2026-01-17"
}
###

### Get All Internships (GET)
GET http://localhost:8080/api/internships/status/APPLIED
###
PUT http://localhost:8080/api/internships/1/status?status=Interview
